#!/bin/bash
# Created by marco, Do 27. Nov 18:38:12 CET 2014.
# Code must go under this line.

test "x$1" = "x" && echo "Syntax: `basename $0` <char>" && echo Outputs the index of the first found character char of input. Counts from 0. && exit 1

text=$(cat)

for i in $(seq 0 $(expr length "${text}")); do
  char="${text:$i:1}"
  test "$char" = "$1" && echo $i && exit 0
done
